name: daily hacker news

on: 
  workflow_dispatch:
#  push:
#    branches:
#      - master
  schedule:
    - cron: '0 7 * * *'

jobs:
  get_top_stories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: pip install
        run: pip install -r requirements.txt
      - name: get started
        run: python main.py
        env:
          ACCESS_TOKEN: ${{ secrets.SECRET }}
